In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [29]:
data = pd.read_csv('DATASET.csv')
data_test = pd.read_csv('Test_data_2.csv')

In [30]:
data_test

Pixel-X  Pixel-Y  Longitude   Latitude      B1      B2      B3      B4  \
0        0.5      0.5  77.001576  12.000585  0.1517  0.1544  0.1648  0.1584   
1        1.5      0.5  77.002126  12.000581  0.1556  0.1624  0.1740  0.1696   
2        3.5      0.5  77.003228  12.000573  0.1545  0.1691  0.1777  0.1860   
3        4.5      0.5  77.003779  12.000569  0.1526  0.1628  0.1730  0.1678   
4        7.5      0.5  77.005431  12.000557  0.1566  0.1614  0.1744  0.1696   
..       ...      ...        ...        ...     ...     ...     ...     ...   
119      6.5     11.5  77.004837  11.994596  0.1582  0.1610  0.1809  0.1690   
120      7.5     11.5  77.005387  11.994592  0.1605  0.1698  0.1933  0.1929   
121     13.5     11.5  77.008692  11.994568  0.1705  0.1678  0.1878  0.1778   
122     17.5     11.5  77.010896  11.994553  0.1622  0.1704  0.1867  0.1850   
123     18.5     11.5  77.011446  11.994549  0.1591  0.1686  0.1848  0.1692   

         B5      B6  ...    GOSAVI     GSAVI     MSAVI     OSAVI       RVI  \
0    0.1982  0.2670  ...  0.235114  0.215637  0.206670  0.269932  1.912879   
1    0.2078  0.2913  ...  0.249037  0.233462  0.222263  0.281020  1.941038   
2    0.2071  0.2667  ...  0.225859  0.210586  0.179447  0.228357  1.701075   
3    0.2028  0.2819  ...  0.256304  0.240754  0.230865  0.290789  1.988081   
4    0.2110  0.3212  ...  0.303418  0.292391  0.283673  0.342333  2.232311   
..      ...     ...  ...       ...       ...       ...       ...       ...   
119  0.2165  0.3409  ...  0.332872  0.328604  0.334620  0.390068  2.492899   
120  0.2347  0.3370  ...  0.274108  0.267484  0.252843  0.301521  1.993779   
121  0.2576  0.3460  ...  0.305299  0.300148  0.301852  0.355459  2.281215   
122  0.2205  0.3266  ...  0.251403  0.240493  0.226472  0.278440  1.904865   
123  0.2083  0.3229  ...  0.262651  0.251911  0.260681  0.320163  2.122931   

         SAVI      WDVI      PSRI        CI     HMSSI  
0    0.210245  0.183883  0.014981  0.025252  1.685606  
1    0.224963  0.201661  0.024717  0.042453  1.717571  
2    0.183265  0.176528  0.063367  0.090860  1.433871  
3    0.233207  0.207414  0.017737  0.029797  1.679976  
4    0.283164  0.251061  0.025529  0.048349  1.893868  
..        ...       ...       ...       ...       ...  
119  0.330888  0.294212  0.023467  0.047337  2.017160  
120  0.253883  0.239539  0.068546  0.119751  1.747019  
121  0.300333  0.271894  0.028902  0.056243  1.946007  
122  0.228743  0.213280  0.044703  0.078919  1.765405  
123  0.261489  0.231962  0.001858  0.003546  1.908392  

[124 rows x 31 columns]

In [31]:
x = data.iloc[:,4:30]
x_test = data_test.iloc[:,4:30]

In [32]:
x

B1      B2      B3      B4      B5      B6      B7      B8     B8A  \
0     0.1618  0.1589  0.1816  0.1558  0.2191  0.3728  0.4361  0.4644  0.4675   
1     0.1708  0.1834  0.2009  0.2122  0.2463  0.3514  0.3953  0.3832  0.4309   
2     0.1686  0.1736  0.1910  0.1914  0.2369  0.3316  0.3805  0.3500  0.4032   
3     0.1587  0.1714  0.1933  0.1889  0.2393  0.3483  0.3982  0.4019  0.4320   
4     0.1613  0.1695  0.1924  0.1857  0.2366  0.3337  0.3755  0.4085  0.4094   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
4849  0.1500  0.1618  0.1804  0.1694  0.2142  0.3591  0.4224  0.4444  0.4555   
4850  0.1501  0.1585  0.1786  0.1612  0.2049  0.3606  0.4380  0.4372  0.4624   
4851  0.1558  0.1546  0.1739  0.1614  0.2028  0.3473  0.4212  0.4272  0.4524   
4852  0.1567  0.1590  0.1788  0.1677  0.2112  0.3426  0.4079  0.4240  0.4381   
4853  0.1553  0.1590  0.1780  0.1618  0.2072  0.3530  0.4433  0.4504  0.4667   

          B9  ...     GNDVI    GOSAVI     GSAVI     MSAVI     OSAVI       RVI  \
0     0.3873  ...  0.437771  0.369191  0.371551  0.405054  0.458826  2.980745   
1     0.3883  ...  0.312104  0.258912  0.253418  0.221352  0.262589  1.805843   
2     0.3985  ...  0.293900  0.240545  0.230340  0.213368  0.262298  1.828631   
3     0.4234  ...  0.350470  0.291667  0.286990  0.279466  0.329089  2.127581   
4     0.3940  ...  0.359627  0.299764  0.295743  0.292243  0.342678  2.199784   
...      ...  ...       ...       ...       ...       ...       ...       ...   
4849  0.4071  ...  0.422535  0.354458  0.353495  0.359685  0.412251  2.623377   
4850  0.4055  ...  0.419942  0.351454  0.349103  0.365935  0.422152  2.712159   
4851  0.4330  ...  0.421394  0.351269  0.346589  0.354400  0.411873  2.646840   
4852  0.4227  ...  0.406768  0.339236  0.334980  0.339897  0.395514  2.528324   
4853  0.4746  ...  0.433482  0.363976  0.363560  0.379383  0.433535  2.783683   

          SAVI      WDVI      PSRI        CI  
0     0.395729  0.347238 -0.008315 -0.019897  
1     0.223398  0.223626  0.081958  0.135721  
2     0.216034  0.206067  0.053679  0.092999  
3     0.279241  0.259847  0.050244  0.092642  
4     0.291336  0.268854  0.048547  0.087238  
...        ...       ...       ...       ...  
4849  0.354328  0.317011  0.021164  0.044864  
4850  0.359755  0.315978  0.007488  0.016749  
4851  0.349045  0.305827  0.019580  0.042131  
4852  0.335777  0.297890  0.025394  0.051878  
4853  0.372297  0.328726  0.007932  0.017305  

[4854 rows x 26 columns]

In [33]:
from pso import ParticleSwarmOptimizedClustering
from particle import quantization_error, calc_sse
from utils import normalize
from kmeans import KMeans
from sklearn.metrics import silhouette_score

In [34]:
x = x.values
x = normalize(x)

In [35]:
x

array([[0.35018051, 0.23042169, 0.27933541, ..., 0.70348108, 0.09067918,
        0.12261025],
       [0.51263538, 0.59939759, 0.47975078, ..., 0.29753303, 0.47529165,
        0.59219634],
       [0.47292419, 0.45180723, 0.37694704, ..., 0.23987073, 0.35480913,
        0.46328042],
       ...,
       [0.24187726, 0.16566265, 0.19937695, ..., 0.5674855 , 0.20952709,
        0.30978496],
       [0.25812274, 0.23192771, 0.25025961, ..., 0.54141819, 0.23429952,
        0.33919682],
       [0.23285199, 0.23192771, 0.24195223, ..., 0.64268714, 0.15990199,
        0.23487097]])

In [36]:
x_test = x_test.values
x_test = normalize(x_test)

In [37]:
x_test

array([[0.18614719, 0.13888889, 0.10194175, ..., 0.05186956, 0.19254456,
        0.22778584],
       [0.35497835, 0.41666667, 0.32524272, ..., 0.12453654, 0.26226541,
        0.30582618],
       [0.30735931, 0.64930556, 0.41504854, ..., 0.02180471, 0.53906024,
        0.52545841],
       ...,
       [1.        , 0.60416667, 0.66019417, ..., 0.41162061, 0.29223637,
        0.36839465],
       [0.64069264, 0.69444444, 0.63349515, ..., 0.1720307 , 0.40539739,
        0.47127903],
       [0.50649351, 0.63194444, 0.58737864, ..., 0.24839283, 0.09856367,
        0.12930086]])

In [11]:
pso = ParticleSwarmOptimizedClustering(
        n_cluster=5, n_particles=10, data=x, hybrid=True, max_iter=1000, print_debug=50)

In [12]:
hist = pso.run()

Initial global best score 0.38279860062371296
Iteration 0001/1000 current gbest score 0.382798600623712959
Iteration 0051/1000 current gbest score 0.379287520857801541
Iteration 0101/1000 current gbest score 0.379095371170993289
Iteration 0151/1000 current gbest score 0.379067165708641962
Iteration 0201/1000 current gbest score 0.379059179952626502
Iteration 0251/1000 current gbest score 0.379057177611186291
Iteration 0301/1000 current gbest score 0.379057152109649520
Iteration 0351/1000 current gbest score 0.379057141469008041
Iteration 0401/1000 current gbest score 0.379057141220448035
Iteration 0451/1000 current gbest score 0.379057141026491184
Iteration 0501/1000 current gbest score 0.379057141002106524
Iteration 0551/1000 current gbest score 0.379057141001640452
Iteration 0601/1000 current gbest score 0.379057140999079223
Iteration 0651/1000 current gbest score 0.379057140998817488
Iteration 0701/1000 current gbest score 0.379057140998806941
Iteration 0751/1000 current gbest score

In [13]:
pso_kmeans = KMeans(n_cluster=5, init_pp=False, seed=2018)

In [14]:
pso_kmeans.centroid = pso.gbest_centroids.copy()
pso_kmeans.centroid

array([[0.23802267, 0.22328186, 0.18160165, 0.16919041, 0.23153902,
        0.16458596, 0.17901822, 0.2282148 , 0.18962779, 0.38137935,
        0.20013024, 0.20868694, 0.25235828, 0.2518694 , 0.32735166,
        0.74435021, 0.37035741, 0.34291217, 0.30536405, 0.33415963,
        0.39879269, 0.3057476 , 0.34411852, 0.25182102, 0.18937384,
        0.26181152],
       [0.44121068, 0.42085461, 0.38713924, 0.36207434, 0.510075  ,
        0.3715932 , 0.38206174, 0.48279647, 0.42453838, 0.56525544,
        0.44160112, 0.41785647, 0.4622901 , 0.47695852, 0.45970985,
        0.6279977 , 0.53812359, 0.52934948, 0.51311784, 0.499171  ,
        0.52738038, 0.39213834, 0.50822094, 0.45711645, 0.31345152,
        0.42656901],
       [0.38808549, 0.43817171, 0.38109611, 0.40460078, 0.468845  ,
        0.29098234, 0.29414834, 0.35078779, 0.33160243, 0.51717408,
        0.42985598, 0.42049351, 0.34828101, 0.32446482, 0.30544281,
        0.52475965, 0.38208456, 0.37287668, 0.35676659, 0.33674651,
      

In [15]:
predicted_pso = pso_kmeans.predict(x)

In [38]:
predicted_pso_test = pso_kmeans.predict(x_test)

In [39]:
predicted_pso

array([4, 2, 2, ..., 4, 4, 4], dtype=int64)

In [40]:
predicted_pso_test

array([0, 0, 2, 0, 1, 2, 2, 1, 1, 2, 2, 0, 0, 4, 2, 2, 3, 0, 2, 2, 2, 4,
       1, 4, 1, 2, 1, 4, 4, 2, 3, 1, 4, 3, 1, 2, 2, 2, 2, 2, 3, 0, 0, 1,
       2, 4, 1, 2, 2, 2, 1, 1, 0, 1, 2, 2, 2, 1, 2, 2, 2, 2, 4, 0, 2, 0,
       2, 0, 2, 2, 2, 3, 0, 0, 1, 4, 2, 2, 2, 2, 1, 1, 1, 0, 1, 3, 2, 0,
       0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 4, 0, 3, 0, 0, 0, 0, 3, 4, 2, 2, 2,
       2, 1, 2, 2, 1, 0, 0, 0, 4, 1, 2, 1, 2, 0], dtype=int64)

In [41]:
result = pd.DataFrame(predicted_pso,columns=['Group'])
result_test = pd.DataFrame(predicted_pso_test,columns=['Group'])

In [42]:
result

Group
0         4
1         2
2         2
3         1
4         1
...     ...
4849      4
4850      4
4851      4
4852      4
4853      4

[4854 rows x 1 columns]

In [43]:
result_test

Group
0        0
1        0
2        2
3        0
4        1
..     ...
119      1
120      2
121      1
122      2
123      0

[124 rows x 1 columns]

In [44]:
result['Group'].unique()

array([4, 2, 1, 3, 0], dtype=int64)

In [45]:
data

Pixel-X  Pixel-Y  Longitude   Latitude      B1      B2      B3      B4  \
0        51.5      0.5  76.963249  12.032853  0.1618  0.1589  0.1816  0.1558   
1        63.5      0.5  76.969860  12.032806  0.1708  0.1834  0.2009  0.2122   
2        64.5      0.5  76.970411  12.032802  0.1686  0.1736  0.1910  0.1914   
3        67.5      0.5  76.972063  12.032790  0.1587  0.1714  0.1933  0.1889   
4        68.5      0.5  76.972614  12.032786  0.1613  0.1695  0.1924  0.1857   
...       ...      ...        ...        ...     ...     ...     ...     ...   
4849    195.5    117.5  77.042100  11.968839  0.1500  0.1618  0.1804  0.1694   
4850    196.5    117.5  77.042651  11.968835  0.1501  0.1585  0.1786  0.1612   
4851    197.5    117.5  77.043202  11.968831  0.1558  0.1546  0.1739  0.1614   
4852    198.5    117.5  77.043753  11.968827  0.1567  0.1590  0.1788  0.1677   
4853    199.5    117.5  77.044303  11.968823  0.1553  0.1590  0.1780  0.1618   

          B5      B6  ...    GOSAVI     GSAVI     MSAVI     OSAVI       RVI  \
0     0.2191  0.3728  ...  0.369191  0.371551  0.405054  0.458826  2.980745   
1     0.2463  0.3514  ...  0.258912  0.253418  0.221352  0.262589  1.805843   
2     0.2369  0.3316  ...  0.240545  0.230340  0.213368  0.262298  1.828631   
3     0.2393  0.3483  ...  0.291667  0.286990  0.279466  0.329089  2.127581   
4     0.2366  0.3337  ...  0.299764  0.295743  0.292243  0.342678  2.199784   
...      ...     ...  ...       ...       ...       ...       ...       ...   
4849  0.2142  0.3591  ...  0.354458  0.353495  0.359685  0.412251  2.623377   
4850  0.2049  0.3606  ...  0.351454  0.349103  0.365935  0.422152  2.712159   
4851  0.2028  0.3473  ...  0.351269  0.346589  0.354400  0.411873  2.646840   
4852  0.2112  0.3426  ...  0.339236  0.334980  0.339897  0.395514  2.528324   
4853  0.2072  0.3530  ...  0.363976  0.363560  0.379383  0.433535  2.783683   

          SAVI      WDVI      PSRI        CI     HMSSI  
0     0.395729  0.347238 -0.008315 -0.019897  2.392811  
1     0.223398  0.223626  0.081958  0.135721  1.655985  
2     0.216034  0.206067  0.053679  0.092999  1.732497  
3     0.279241  0.259847  0.050244  0.092642  1.843833  
4     0.291336  0.268854  0.048547  0.087238  1.796984  
...        ...       ...       ...       ...       ...  
4849  0.354328  0.317011  0.021164  0.044864  2.119835  
4850  0.359755  0.315978  0.007488  0.016749  2.236973  
4851  0.349045  0.305827  0.019580  0.042131  2.151797  
4852  0.335777  0.297890  0.025394  0.051878  2.042934  
4853  0.372297  0.328726  0.007932  0.017305  2.181706  

[4854 rows x 31 columns]

In [46]:
result

Group
0         4
1         2
2         2
3         1
4         1
...     ...
4849      4
4850      4
4851      4
4852      4
4853      4

[4854 rows x 1 columns]

In [47]:
data['Cluster'] = result['Group']
data_test['Cluster'] = result_test['Group']

In [48]:
data

Pixel-X  Pixel-Y  Longitude   Latitude      B1      B2      B3      B4  \
0        51.5      0.5  76.963249  12.032853  0.1618  0.1589  0.1816  0.1558   
1        63.5      0.5  76.969860  12.032806  0.1708  0.1834  0.2009  0.2122   
2        64.5      0.5  76.970411  12.032802  0.1686  0.1736  0.1910  0.1914   
3        67.5      0.5  76.972063  12.032790  0.1587  0.1714  0.1933  0.1889   
4        68.5      0.5  76.972614  12.032786  0.1613  0.1695  0.1924  0.1857   
...       ...      ...        ...        ...     ...     ...     ...     ...   
4849    195.5    117.5  77.042100  11.968839  0.1500  0.1618  0.1804  0.1694   
4850    196.5    117.5  77.042651  11.968835  0.1501  0.1585  0.1786  0.1612   
4851    197.5    117.5  77.043202  11.968831  0.1558  0.1546  0.1739  0.1614   
4852    198.5    117.5  77.043753  11.968827  0.1567  0.1590  0.1788  0.1677   
4853    199.5    117.5  77.044303  11.968823  0.1553  0.1590  0.1780  0.1618   

          B5      B6  ...     GSAVI     MSAVI     OSAVI       RVI      SAVI  \
0     0.2191  0.3728  ...  0.371551  0.405054  0.458826  2.980745  0.395729   
1     0.2463  0.3514  ...  0.253418  0.221352  0.262589  1.805843  0.223398   
2     0.2369  0.3316  ...  0.230340  0.213368  0.262298  1.828631  0.216034   
3     0.2393  0.3483  ...  0.286990  0.279466  0.329089  2.127581  0.279241   
4     0.2366  0.3337  ...  0.295743  0.292243  0.342678  2.199784  0.291336   
...      ...     ...  ...       ...       ...       ...       ...       ...   
4849  0.2142  0.3591  ...  0.353495  0.359685  0.412251  2.623377  0.354328   
4850  0.2049  0.3606  ...  0.349103  0.365935  0.422152  2.712159  0.359755   
4851  0.2028  0.3473  ...  0.346589  0.354400  0.411873  2.646840  0.349045   
4852  0.2112  0.3426  ...  0.334980  0.339897  0.395514  2.528324  0.335777   
4853  0.2072  0.3530  ...  0.363560  0.379383  0.433535  2.783683  0.372297   

          WDVI      PSRI        CI     HMSSI  Cluster  
0     0.347238 -0.008315 -0.019897  2.392811        4  
1     0.223626  0.081958  0.135721  1.655985        2  
2     0.206067  0.053679  0.092999  1.732497        2  
3     0.259847  0.050244  0.092642  1.843833        1  
4     0.268854  0.048547  0.087238  1.796984        1  
...        ...       ...       ...       ...      ...  
4849  0.317011  0.021164  0.044864  2.119835        4  
4850  0.315978  0.007488  0.016749  2.236973        4  
4851  0.305827  0.019580  0.042131  2.151797        4  
4852  0.297890  0.025394  0.051878  2.042934        4  
4853  0.328726  0.007932  0.017305  2.181706        4  

[4854 rows x 32 columns]

In [27]:
data_test

Pixel-X  Pixel-Y  Longitude   Latitude      B1      B2      B3      B4  \
0       5.5      0.5  77.004330  12.000565  0.1564  0.1694  0.1854  0.2028   
1       5.5      1.5  77.004326  12.000023  0.1598  0.1560  0.1666  0.1648   
2       6.5      1.5  77.004877  12.000019  0.1586  0.1760  0.1960  0.2108   
3       7.5      1.5  77.005427  12.000015  0.1573  0.1625  0.1821  0.1638   
4       5.5      2.5  77.004322  11.999480  0.1646  0.1754  0.1886  0.1936   
5       7.5      2.5  77.005423  11.999473  0.1591  0.1612  0.1798  0.1654   
6       4.5      3.5  77.003767  11.998942  0.1696  0.1845  0.2102  0.2262   
7       6.5      3.5  77.004869  11.998934  0.1636  0.1758  0.1941  0.2016   
8       4.5      4.5  77.003763  11.998400  0.1689  0.1868  0.2122  0.2254   
9       5.5      4.5  77.004314  11.998396  0.1642  0.1755  0.2018  0.1984   
10      6.5      4.5  77.004865  11.998392  0.1654  0.1738  0.1980  0.2048   
11      9.5      6.5  77.006509  11.997296  0.1630  0.1734  0.1930  0.2026   
12     10.5      6.5  77.007060  11.997292  0.1627  0.1772  0.1951  0.2106   
13     11.5      6.5  77.007611  11.997288  0.1606  0.1736  0.1920  0.2064   
14      9.5      7.5  77.006505  11.996753  0.1605  0.1706  0.1864  0.1810   
15     10.5      7.5  77.007056  11.996749  0.1596  0.1666  0.1876  0.1826   
16      8.5      8.5  77.005950  11.996215  0.1587  0.1714  0.1954  0.2086   
17     10.5      8.5  77.007052  11.996207  0.1581  0.1675  0.1826  0.1764   
18      8.5      9.5  77.005946  11.995673  0.1609  0.1712  0.1930  0.1934   
19      9.5      9.5  77.006497  11.995669  0.1638  0.1736  0.1920  0.1944   
20      9.5     10.5  77.006493  11.995126  0.1680  0.1728  0.1919  0.1976   

        B5      B6  ...     GSAVI     MSAVI     OSAVI       RVI      SAVI  \
0   0.2342  0.2777  ...  0.227434  0.183342  0.226454  1.676529  0.186678   
1   0.2021  0.2602  ...  0.188087  0.172089  0.228805  1.729976  0.176626   
2   0.2421  0.3027  ...  0.214862  0.176462  0.216425  1.632827  0.179777   
3   0.2079  0.3501  ...  0.341212  0.359180  0.414788  2.656899  0.353599   
4   0.2462  0.3277  ...  0.226494  0.201992  0.249570  1.774793  0.204999   
5   0.2283  0.3438  ...  0.345863  0.357298  0.412262  2.636034  0.351919   
6   0.2705  0.3150  ...  0.189118  0.151330  0.184734  1.512821  0.154709   
7   0.2448  0.3307  ...  0.252487  0.225205  0.270414  1.849206  0.227274   
8   0.2685  0.3114  ...  0.200973  0.167378  0.202271  1.572316  0.170543   
9   0.2524  0.3581  ...  0.314539  0.307666  0.351427  2.219758  0.306093   
10  0.2360  0.2970  ...  0.216245  0.190198  0.233042  1.699219  0.193317   
11  0.2515  0.3361  ...  0.267750  0.237435  0.282313  1.897335  0.239028   
12  0.2424  0.2853  ...  0.176211  0.137342  0.173474  1.485280  0.141217   
13  0.2263  0.2840  ...  0.162432  0.125278  0.160830  1.446705  0.129305   
14  0.2262  0.3190  ...  0.223743  0.215412  0.268743  1.869613  0.218190   
15  0.2253  0.3171  ...  0.270508  0.262688  0.315721  2.075575  0.263322   
16  0.2393  0.3248  ...  0.245512  0.209580  0.251887  1.767497  0.212065   
17  0.2086  0.3029  ...  0.194256  0.186903  0.240322  1.759637  0.190749   
18  0.2411  0.3172  ...  0.252665  0.236311  0.284879  1.920372  0.238060   
19  0.2430  0.3256  ...  0.268486  0.249290  0.297388  1.973251  0.250476   
20  0.2525  0.3332  ...  0.281143  0.257176  0.303802  1.996963  0.257990   

        WDVI      PSRI        CI     HMSSI  Cluster  
0   0.187494  0.120274  0.164694  1.369329        2  
1   0.161170  0.033820  0.053398  1.578884        0  
2   0.185678  0.114965  0.165085  1.435958        2  
3   0.312022  0.003713  0.007937  2.137363        4  
4   0.198013  0.055539  0.094008  1.692665        2  
5   0.311619  0.012216  0.025393  2.078597        4  
6   0.172098  0.132381  0.184350  1.392573        2  
7   0.221197  0.078016  0.127976  1.640377        1  
8   0.184899  0.123956  0.171251  1.381544        2  
9   0.291203  0.063949  0.115423  1.804939        4 

In [49]:
data.to_csv("PSO_Data_2.csv")
data_test.to_csv("test_data_PSO_2_128.csv")